name: Frontend CI

on:
  push:
    branches:
      - main
      - master
      - feature/galaxy-background

  pull_request:
    branches:
      - main
      - master
      - feature/galaxy-background

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        working-directory: frontend
        run: npm install

      - name: Build React Application
        working-directory: frontend
        run: npm run build
